// <auto-generated />
using System;
using Catalog.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Repository.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20181207012317_AddCustomer")]
    partial class AddCustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("354d06be-9c1d-4b8b-a7d7-79f10c5beebb"),
                            Name = "João da Silva"
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6a9c498-26a3-406a-8458-fb53387f8668"),
                            Description = "Notebook Avell G1513 FOX-5 BS",
                            Name = "Notebook Avell G1513 FOX-5 BS",
                            Price = 4799.70m
                        },
                        new
                        {
                            Id = new Guid("18bbadd7-b805-4757-9951-e5ab706316b7"),
                            Description = "Smartphone ASUS ZenFone 5Z 8GB/256GB Preto",
                            Name = "Smartphone ASUS ZenFone 5Z 8GB/256GB Preto",
                            Price = 3509.10m
                        },
                        new
                        {
                            Id = new Guid("f21974a6-4e97-4703-a36e-2ccc03a5ba3d"),
                            Description = "Console Xbox One X 1TB 4K+ Controle sem Fio",
                            Name = "Console Xbox One X 1TB 4K+ Controle sem Fio",
                            Price = 2540.19m
                        },
                        new
                        {
                            Id = new Guid("ba27bf30-c2da-48f5-b756-d28c6df7622a"),
                            Description = "Console Playstation 4 Pro 1tb - Ps4",
                            Name = "Console Playstation 4 Pro 1tb - Ps4",
                            Price = 2640.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
