// <auto-generated />
using System;
using Catalog.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Repository.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20181206133817_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6ea2289-1551-473c-9123-8634790a81ba"),
                            Description = "Notebook Avell G1513 FOX-5 BS",
                            Name = "Notebook Avell G1513 FOX-5 BS",
                            Price = 4799.70m
                        },
                        new
                        {
                            Id = new Guid("11253e54-ed71-466c-9e7a-430fc14a17b9"),
                            Description = "Smartphone ASUS ZenFone 5Z 8GB/256GB Preto",
                            Name = "Smartphone ASUS ZenFone 5Z 8GB/256GB Preto",
                            Price = 3509.10m
                        },
                        new
                        {
                            Id = new Guid("7e9729b8-9704-4a0b-ae39-036cacae09f6"),
                            Description = "Console Xbox One X 1TB 4K+ Controle sem Fio",
                            Name = "Console Xbox One X 1TB 4K+ Controle sem Fio",
                            Price = 2540.19m
                        },
                        new
                        {
                            Id = new Guid("3e5ff496-e40d-4a59-baf9-30081918f445"),
                            Description = "Console Playstation 4 Pro 1tb - Ps4",
                            Name = "Console Playstation 4 Pro 1tb - Ps4",
                            Price = 2640.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
